//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_Model.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is required!.
        /// </summary>
        public static string err_address_street {
            get {
                return ResourceManager.GetString("err_address_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required!.
        /// </summary>
        public static string err_country_street {
            get {
                return ResourceManager.GetString("err_country_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality is required!.
        /// </summary>
        public static string err_locality_street {
            get {
                return ResourceManager.GetString("err_locality_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required!.
        /// </summary>
        public static string err_state_street {
            get {
                return ResourceManager.GetString("err_state_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip is required!.
        /// </summary>
        public static string err_zip_street {
            get {
                return ResourceManager.GetString("err_zip_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string label_birthday {
            get {
                return ResourceManager.GetString("label_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country  Address.
        /// </summary>
        public static string label_country {
            get {
                return ResourceManager.GetString("label_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string label_identification {
            get {
                return ResourceManager.GetString("label_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string label_last_name {
            get {
                return ResourceManager.GetString("label_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality Address.
        /// </summary>
        public static string label_locality {
            get {
                return ResourceManager.GetString("label_locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string label_middle_name {
            get {
                return ResourceManager.GetString("label_middle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Address.
        /// </summary>
        public static string label_state {
            get {
                return ResourceManager.GetString("label_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string label_street {
            get {
                return ResourceManager.GetString("label_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Address.
        /// </summary>
        public static string label_zip {
            get {
                return ResourceManager.GetString("label_zip", resourceCulture);
            }
        }
    }
}
